//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenekRH.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        public int NominaId { get; set; }
        public decimal Percepciones { get; set; }
        public decimal Retenciones { get; set; }
        public decimal Total { get; set; }
        public int NumeroEmpleado { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
