//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.WinForms.WSTenekRH {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NominaEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NominaEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal PercepcionesField;
        
        private decimal RetencionesField;
        
        private decimal TotalField;
        
        private int NumeroEmpleadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Percepciones {
            get {
                return this.PercepcionesField;
            }
            set {
                if ((this.PercepcionesField.Equals(value) != true)) {
                    this.PercepcionesField = value;
                    this.RaisePropertyChanged("Percepciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Retenciones {
            get {
                return this.RetencionesField;
            }
            set {
                if ((this.RetencionesField.Equals(value) != true)) {
                    this.RetencionesField = value;
                    this.RaisePropertyChanged("Retenciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int NumeroEmpleado {
            get {
                return this.NumeroEmpleadoField;
            }
            set {
                if ((this.NumeroEmpleadoField.Equals(value) != true)) {
                    this.NumeroEmpleadoField = value;
                    this.RaisePropertyChanged("NumeroEmpleado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpleadoEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EmpleadoEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NumeroEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresEmpleadoField;
        
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerfilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumeroEmpleado {
            get {
                return this.NumeroEmpleadoField;
            }
            set {
                if ((this.NumeroEmpleadoField.Equals(value) != true)) {
                    this.NumeroEmpleadoField = value;
                    this.RaisePropertyChanged("NumeroEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ApellidosEmpleado {
            get {
                return this.ApellidosEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosEmpleadoField, value) != true)) {
                    this.ApellidosEmpleadoField = value;
                    this.RaisePropertyChanged("ApellidosEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombresEmpleado {
            get {
                return this.NombresEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresEmpleadoField, value) != true)) {
                    this.NombresEmpleadoField = value;
                    this.RaisePropertyChanged("NombresEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Mensajeria {
            get {
                return this.MensajeriaField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeriaField, value) != true)) {
                    this.MensajeriaField = value;
                    this.RaisePropertyChanged("Mensajeria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Puesto {
            get {
                return this.PuestoField;
            }
            set {
                if ((object.ReferenceEquals(this.PuestoField, value) != true)) {
                    this.PuestoField = value;
                    this.RaisePropertyChanged("Puesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Perfil {
            get {
                return this.PerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilField, value) != true)) {
                    this.PerfilField = value;
                    this.RaisePropertyChanged("Perfil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventosEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EventosEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        private System.DateTime FechaInicioField;
        
        private System.DateTime FechaFinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DirectorioEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DirectorioEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JefeDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoDepartamentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreDepartamento {
            get {
                return this.NombreDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDepartamentoField, value) != true)) {
                    this.NombreDepartamentoField = value;
                    this.RaisePropertyChanged("NombreDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string JefeDepartamento {
            get {
                return this.JefeDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.JefeDepartamentoField, value) != true)) {
                    this.JefeDepartamentoField = value;
                    this.RaisePropertyChanged("JefeDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TelefonoDepartamento {
            get {
                return this.TelefonoDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoDepartamentoField, value) != true)) {
                    this.TelefonoDepartamentoField = value;
                    this.RaisePropertyChanged("TelefonoDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CorreoDepartamento {
            get {
                return this.CorreoDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoDepartamentoField, value) != true)) {
                    this.CorreoDepartamentoField = value;
                    this.RaisePropertyChanged("CorreoDepartamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacacionesEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VacacionesEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> NumeroEmpleadoField;
        
        private int PeriodoField;
        
        private int DiasCorrespondientesField;
        
        private int DiasDisponiblesField;
        
        private int DiasDisfrutadosField;
        
        private decimal PorcentajePrimaField;
        
        private int VencimientoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> NumeroEmpleado {
            get {
                return this.NumeroEmpleadoField;
            }
            set {
                if ((this.NumeroEmpleadoField.Equals(value) != true)) {
                    this.NumeroEmpleadoField = value;
                    this.RaisePropertyChanged("NumeroEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Periodo {
            get {
                return this.PeriodoField;
            }
            set {
                if ((this.PeriodoField.Equals(value) != true)) {
                    this.PeriodoField = value;
                    this.RaisePropertyChanged("Periodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int DiasCorrespondientes {
            get {
                return this.DiasCorrespondientesField;
            }
            set {
                if ((this.DiasCorrespondientesField.Equals(value) != true)) {
                    this.DiasCorrespondientesField = value;
                    this.RaisePropertyChanged("DiasCorrespondientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int DiasDisponibles {
            get {
                return this.DiasDisponiblesField;
            }
            set {
                if ((this.DiasDisponiblesField.Equals(value) != true)) {
                    this.DiasDisponiblesField = value;
                    this.RaisePropertyChanged("DiasDisponibles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int DiasDisfrutados {
            get {
                return this.DiasDisfrutadosField;
            }
            set {
                if ((this.DiasDisfrutadosField.Equals(value) != true)) {
                    this.DiasDisfrutadosField = value;
                    this.RaisePropertyChanged("DiasDisfrutados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal PorcentajePrima {
            get {
                return this.PorcentajePrimaField;
            }
            set {
                if ((this.PorcentajePrimaField.Equals(value) != true)) {
                    this.PorcentajePrimaField = value;
                    this.RaisePropertyChanged("PorcentajePrima");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Vencimiento {
            get {
                return this.VencimientoField;
            }
            set {
                if ((this.VencimientoField.Equals(value) != true)) {
                    this.VencimientoField = value;
                    this.RaisePropertyChanged("Vencimiento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSTenekRH.ServicesSoap")]
    public interface ServicesSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Test.WinForms.WSTenekRH.HelloWorldResponse HelloWorld(Test.WinForms.WSTenekRH.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.HelloWorldResponse> HelloWorldAsync(Test.WinForms.WSTenekRH.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        Test.WinForms.WSTenekRH.LoginResponse Login(Test.WinForms.WSTenekRH.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.LoginResponse> LoginAsync(Test.WinForms.WSTenekRH.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name numeroEmpleado from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraeNomina", ReplyAction="*")]
        Test.WinForms.WSTenekRH.TraeNominaResponse TraeNomina(Test.WinForms.WSTenekRH.TraeNominaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraeNomina", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.TraeNominaResponse> TraeNominaAsync(Test.WinForms.WSTenekRH.TraeNominaRequest request);
        
        // CODEGEN: Generating message contract since element name numeroEmpleado from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraeEmpleado", ReplyAction="*")]
        Test.WinForms.WSTenekRH.TraeEmpleadoResponse TraeEmpleado(Test.WinForms.WSTenekRH.TraeEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraeEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.TraeEmpleadoResponse> TraeEmpleadoAsync(Test.WinForms.WSTenekRH.TraeEmpleadoRequest request);
        
        // CODEGEN: Generating message contract since element name TraeLitaEventosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraeLitaEventos", ReplyAction="*")]
        Test.WinForms.WSTenekRH.TraeLitaEventosResponse TraeLitaEventos(Test.WinForms.WSTenekRH.TraeLitaEventosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraeLitaEventos", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.TraeLitaEventosResponse> TraeLitaEventosAsync(Test.WinForms.WSTenekRH.TraeLitaEventosRequest request);
        
        // CODEGEN: Generating message contract since element name TraeListaDirectorioResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraeListaDirectorio", ReplyAction="*")]
        Test.WinForms.WSTenekRH.TraeListaDirectorioResponse TraeListaDirectorio(Test.WinForms.WSTenekRH.TraeListaDirectorioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraeListaDirectorio", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.TraeListaDirectorioResponse> TraeListaDirectorioAsync(Test.WinForms.WSTenekRH.TraeListaDirectorioRequest request);
        
        // CODEGEN: Generating message contract since element name numeroEmpleado from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraeVacaciones", ReplyAction="*")]
        Test.WinForms.WSTenekRH.TraeVacacionesResponse TraeVacaciones(Test.WinForms.WSTenekRH.TraeVacacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraeVacaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.TraeVacacionesResponse> TraeVacacionesAsync(Test.WinForms.WSTenekRH.TraeVacacionesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Test.WinForms.WSTenekRH.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Test.WinForms.WSTenekRH.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.WinForms.WSTenekRH.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Test.WinForms.WSTenekRH.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public Test.WinForms.WSTenekRH.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Test.WinForms.WSTenekRH.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.WinForms.WSTenekRH.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Test.WinForms.WSTenekRH.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraeNominaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraeNomina", Namespace="http://tempuri.org/", Order=0)]
        public Test.WinForms.WSTenekRH.TraeNominaRequestBody Body;
        
        public TraeNominaRequest() {
        }
        
        public TraeNominaRequest(Test.WinForms.WSTenekRH.TraeNominaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraeNominaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroEmpleado;
        
        public TraeNominaRequestBody() {
        }
        
        public TraeNominaRequestBody(string numeroEmpleado) {
            this.numeroEmpleado = numeroEmpleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraeNominaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraeNominaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.WinForms.WSTenekRH.TraeNominaResponseBody Body;
        
        public TraeNominaResponse() {
        }
        
        public TraeNominaResponse(Test.WinForms.WSTenekRH.TraeNominaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraeNominaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Test.WinForms.WSTenekRH.NominaEntity[] TraeNominaResult;
        
        public TraeNominaResponseBody() {
        }
        
        public TraeNominaResponseBody(Test.WinForms.WSTenekRH.NominaEntity[] TraeNominaResult) {
            this.TraeNominaResult = TraeNominaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraeEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraeEmpleado", Namespace="http://tempuri.org/", Order=0)]
        public Test.WinForms.WSTenekRH.TraeEmpleadoRequestBody Body;
        
        public TraeEmpleadoRequest() {
        }
        
        public TraeEmpleadoRequest(Test.WinForms.WSTenekRH.TraeEmpleadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraeEmpleadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroEmpleado;
        
        public TraeEmpleadoRequestBody() {
        }
        
        public TraeEmpleadoRequestBody(string numeroEmpleado) {
            this.numeroEmpleado = numeroEmpleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraeEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraeEmpleadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.WinForms.WSTenekRH.TraeEmpleadoResponseBody Body;
        
        public TraeEmpleadoResponse() {
        }
        
        public TraeEmpleadoResponse(Test.WinForms.WSTenekRH.TraeEmpleadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraeEmpleadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Test.WinForms.WSTenekRH.EmpleadoEntity[] TraeEmpleadoResult;
        
        public TraeEmpleadoResponseBody() {
        }
        
        public TraeEmpleadoResponseBody(Test.WinForms.WSTenekRH.EmpleadoEntity[] TraeEmpleadoResult) {
            this.TraeEmpleadoResult = TraeEmpleadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraeLitaEventosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraeLitaEventos", Namespace="http://tempuri.org/", Order=0)]
        public Test.WinForms.WSTenekRH.TraeLitaEventosRequestBody Body;
        
        public TraeLitaEventosRequest() {
        }
        
        public TraeLitaEventosRequest(Test.WinForms.WSTenekRH.TraeLitaEventosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TraeLitaEventosRequestBody {
        
        public TraeLitaEventosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraeLitaEventosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraeLitaEventosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.WinForms.WSTenekRH.TraeLitaEventosResponseBody Body;
        
        public TraeLitaEventosResponse() {
        }
        
        public TraeLitaEventosResponse(Test.WinForms.WSTenekRH.TraeLitaEventosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraeLitaEventosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Test.WinForms.WSTenekRH.EventosEntity[] TraeLitaEventosResult;
        
        public TraeLitaEventosResponseBody() {
        }
        
        public TraeLitaEventosResponseBody(Test.WinForms.WSTenekRH.EventosEntity[] TraeLitaEventosResult) {
            this.TraeLitaEventosResult = TraeLitaEventosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraeListaDirectorioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraeListaDirectorio", Namespace="http://tempuri.org/", Order=0)]
        public Test.WinForms.WSTenekRH.TraeListaDirectorioRequestBody Body;
        
        public TraeListaDirectorioRequest() {
        }
        
        public TraeListaDirectorioRequest(Test.WinForms.WSTenekRH.TraeListaDirectorioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TraeListaDirectorioRequestBody {
        
        public TraeListaDirectorioRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraeListaDirectorioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraeListaDirectorioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.WinForms.WSTenekRH.TraeListaDirectorioResponseBody Body;
        
        public TraeListaDirectorioResponse() {
        }
        
        public TraeListaDirectorioResponse(Test.WinForms.WSTenekRH.TraeListaDirectorioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraeListaDirectorioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Test.WinForms.WSTenekRH.DirectorioEntity[] TraeListaDirectorioResult;
        
        public TraeListaDirectorioResponseBody() {
        }
        
        public TraeListaDirectorioResponseBody(Test.WinForms.WSTenekRH.DirectorioEntity[] TraeListaDirectorioResult) {
            this.TraeListaDirectorioResult = TraeListaDirectorioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraeVacacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraeVacaciones", Namespace="http://tempuri.org/", Order=0)]
        public Test.WinForms.WSTenekRH.TraeVacacionesRequestBody Body;
        
        public TraeVacacionesRequest() {
        }
        
        public TraeVacacionesRequest(Test.WinForms.WSTenekRH.TraeVacacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraeVacacionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroEmpleado;
        
        public TraeVacacionesRequestBody() {
        }
        
        public TraeVacacionesRequestBody(string numeroEmpleado) {
            this.numeroEmpleado = numeroEmpleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraeVacacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraeVacacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.WinForms.WSTenekRH.TraeVacacionesResponseBody Body;
        
        public TraeVacacionesResponse() {
        }
        
        public TraeVacacionesResponse(Test.WinForms.WSTenekRH.TraeVacacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraeVacacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Test.WinForms.WSTenekRH.VacacionesEntity[] TraeVacacionesResult;
        
        public TraeVacacionesResponseBody() {
        }
        
        public TraeVacacionesResponseBody(Test.WinForms.WSTenekRH.VacacionesEntity[] TraeVacacionesResult) {
            this.TraeVacacionesResult = TraeVacacionesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicesSoapChannel : Test.WinForms.WSTenekRH.ServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesSoapClient : System.ServiceModel.ClientBase<Test.WinForms.WSTenekRH.ServicesSoap>, Test.WinForms.WSTenekRH.ServicesSoap {
        
        public ServicesSoapClient() {
        }
        
        public ServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.WinForms.WSTenekRH.HelloWorldResponse Test.WinForms.WSTenekRH.ServicesSoap.HelloWorld(Test.WinForms.WSTenekRH.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Test.WinForms.WSTenekRH.HelloWorldRequest inValue = new Test.WinForms.WSTenekRH.HelloWorldRequest();
            inValue.Body = new Test.WinForms.WSTenekRH.HelloWorldRequestBody();
            Test.WinForms.WSTenekRH.HelloWorldResponse retVal = ((Test.WinForms.WSTenekRH.ServicesSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.HelloWorldResponse> Test.WinForms.WSTenekRH.ServicesSoap.HelloWorldAsync(Test.WinForms.WSTenekRH.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.HelloWorldResponse> HelloWorldAsync() {
            Test.WinForms.WSTenekRH.HelloWorldRequest inValue = new Test.WinForms.WSTenekRH.HelloWorldRequest();
            inValue.Body = new Test.WinForms.WSTenekRH.HelloWorldRequestBody();
            return ((Test.WinForms.WSTenekRH.ServicesSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.WinForms.WSTenekRH.LoginResponse Test.WinForms.WSTenekRH.ServicesSoap.Login(Test.WinForms.WSTenekRH.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string username, string password) {
            Test.WinForms.WSTenekRH.LoginRequest inValue = new Test.WinForms.WSTenekRH.LoginRequest();
            inValue.Body = new Test.WinForms.WSTenekRH.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Test.WinForms.WSTenekRH.LoginResponse retVal = ((Test.WinForms.WSTenekRH.ServicesSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.LoginResponse> Test.WinForms.WSTenekRH.ServicesSoap.LoginAsync(Test.WinForms.WSTenekRH.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.LoginResponse> LoginAsync(string username, string password) {
            Test.WinForms.WSTenekRH.LoginRequest inValue = new Test.WinForms.WSTenekRH.LoginRequest();
            inValue.Body = new Test.WinForms.WSTenekRH.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Test.WinForms.WSTenekRH.ServicesSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.WinForms.WSTenekRH.TraeNominaResponse Test.WinForms.WSTenekRH.ServicesSoap.TraeNomina(Test.WinForms.WSTenekRH.TraeNominaRequest request) {
            return base.Channel.TraeNomina(request);
        }
        
        public Test.WinForms.WSTenekRH.NominaEntity[] TraeNomina(string numeroEmpleado) {
            Test.WinForms.WSTenekRH.TraeNominaRequest inValue = new Test.WinForms.WSTenekRH.TraeNominaRequest();
            inValue.Body = new Test.WinForms.WSTenekRH.TraeNominaRequestBody();
            inValue.Body.numeroEmpleado = numeroEmpleado;
            Test.WinForms.WSTenekRH.TraeNominaResponse retVal = ((Test.WinForms.WSTenekRH.ServicesSoap)(this)).TraeNomina(inValue);
            return retVal.Body.TraeNominaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.TraeNominaResponse> Test.WinForms.WSTenekRH.ServicesSoap.TraeNominaAsync(Test.WinForms.WSTenekRH.TraeNominaRequest request) {
            return base.Channel.TraeNominaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.TraeNominaResponse> TraeNominaAsync(string numeroEmpleado) {
            Test.WinForms.WSTenekRH.TraeNominaRequest inValue = new Test.WinForms.WSTenekRH.TraeNominaRequest();
            inValue.Body = new Test.WinForms.WSTenekRH.TraeNominaRequestBody();
            inValue.Body.numeroEmpleado = numeroEmpleado;
            return ((Test.WinForms.WSTenekRH.ServicesSoap)(this)).TraeNominaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.WinForms.WSTenekRH.TraeEmpleadoResponse Test.WinForms.WSTenekRH.ServicesSoap.TraeEmpleado(Test.WinForms.WSTenekRH.TraeEmpleadoRequest request) {
            return base.Channel.TraeEmpleado(request);
        }
        
        public Test.WinForms.WSTenekRH.EmpleadoEntity[] TraeEmpleado(string numeroEmpleado) {
            Test.WinForms.WSTenekRH.TraeEmpleadoRequest inValue = new Test.WinForms.WSTenekRH.TraeEmpleadoRequest();
            inValue.Body = new Test.WinForms.WSTenekRH.TraeEmpleadoRequestBody();
            inValue.Body.numeroEmpleado = numeroEmpleado;
            Test.WinForms.WSTenekRH.TraeEmpleadoResponse retVal = ((Test.WinForms.WSTenekRH.ServicesSoap)(this)).TraeEmpleado(inValue);
            return retVal.Body.TraeEmpleadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.TraeEmpleadoResponse> Test.WinForms.WSTenekRH.ServicesSoap.TraeEmpleadoAsync(Test.WinForms.WSTenekRH.TraeEmpleadoRequest request) {
            return base.Channel.TraeEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.TraeEmpleadoResponse> TraeEmpleadoAsync(string numeroEmpleado) {
            Test.WinForms.WSTenekRH.TraeEmpleadoRequest inValue = new Test.WinForms.WSTenekRH.TraeEmpleadoRequest();
            inValue.Body = new Test.WinForms.WSTenekRH.TraeEmpleadoRequestBody();
            inValue.Body.numeroEmpleado = numeroEmpleado;
            return ((Test.WinForms.WSTenekRH.ServicesSoap)(this)).TraeEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.WinForms.WSTenekRH.TraeLitaEventosResponse Test.WinForms.WSTenekRH.ServicesSoap.TraeLitaEventos(Test.WinForms.WSTenekRH.TraeLitaEventosRequest request) {
            return base.Channel.TraeLitaEventos(request);
        }
        
        public Test.WinForms.WSTenekRH.EventosEntity[] TraeLitaEventos() {
            Test.WinForms.WSTenekRH.TraeLitaEventosRequest inValue = new Test.WinForms.WSTenekRH.TraeLitaEventosRequest();
            inValue.Body = new Test.WinForms.WSTenekRH.TraeLitaEventosRequestBody();
            Test.WinForms.WSTenekRH.TraeLitaEventosResponse retVal = ((Test.WinForms.WSTenekRH.ServicesSoap)(this)).TraeLitaEventos(inValue);
            return retVal.Body.TraeLitaEventosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.TraeLitaEventosResponse> Test.WinForms.WSTenekRH.ServicesSoap.TraeLitaEventosAsync(Test.WinForms.WSTenekRH.TraeLitaEventosRequest request) {
            return base.Channel.TraeLitaEventosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.TraeLitaEventosResponse> TraeLitaEventosAsync() {
            Test.WinForms.WSTenekRH.TraeLitaEventosRequest inValue = new Test.WinForms.WSTenekRH.TraeLitaEventosRequest();
            inValue.Body = new Test.WinForms.WSTenekRH.TraeLitaEventosRequestBody();
            return ((Test.WinForms.WSTenekRH.ServicesSoap)(this)).TraeLitaEventosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.WinForms.WSTenekRH.TraeListaDirectorioResponse Test.WinForms.WSTenekRH.ServicesSoap.TraeListaDirectorio(Test.WinForms.WSTenekRH.TraeListaDirectorioRequest request) {
            return base.Channel.TraeListaDirectorio(request);
        }
        
        public Test.WinForms.WSTenekRH.DirectorioEntity[] TraeListaDirectorio() {
            Test.WinForms.WSTenekRH.TraeListaDirectorioRequest inValue = new Test.WinForms.WSTenekRH.TraeListaDirectorioRequest();
            inValue.Body = new Test.WinForms.WSTenekRH.TraeListaDirectorioRequestBody();
            Test.WinForms.WSTenekRH.TraeListaDirectorioResponse retVal = ((Test.WinForms.WSTenekRH.ServicesSoap)(this)).TraeListaDirectorio(inValue);
            return retVal.Body.TraeListaDirectorioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.TraeListaDirectorioResponse> Test.WinForms.WSTenekRH.ServicesSoap.TraeListaDirectorioAsync(Test.WinForms.WSTenekRH.TraeListaDirectorioRequest request) {
            return base.Channel.TraeListaDirectorioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.TraeListaDirectorioResponse> TraeListaDirectorioAsync() {
            Test.WinForms.WSTenekRH.TraeListaDirectorioRequest inValue = new Test.WinForms.WSTenekRH.TraeListaDirectorioRequest();
            inValue.Body = new Test.WinForms.WSTenekRH.TraeListaDirectorioRequestBody();
            return ((Test.WinForms.WSTenekRH.ServicesSoap)(this)).TraeListaDirectorioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.WinForms.WSTenekRH.TraeVacacionesResponse Test.WinForms.WSTenekRH.ServicesSoap.TraeVacaciones(Test.WinForms.WSTenekRH.TraeVacacionesRequest request) {
            return base.Channel.TraeVacaciones(request);
        }
        
        public Test.WinForms.WSTenekRH.VacacionesEntity[] TraeVacaciones(string numeroEmpleado) {
            Test.WinForms.WSTenekRH.TraeVacacionesRequest inValue = new Test.WinForms.WSTenekRH.TraeVacacionesRequest();
            inValue.Body = new Test.WinForms.WSTenekRH.TraeVacacionesRequestBody();
            inValue.Body.numeroEmpleado = numeroEmpleado;
            Test.WinForms.WSTenekRH.TraeVacacionesResponse retVal = ((Test.WinForms.WSTenekRH.ServicesSoap)(this)).TraeVacaciones(inValue);
            return retVal.Body.TraeVacacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.TraeVacacionesResponse> Test.WinForms.WSTenekRH.ServicesSoap.TraeVacacionesAsync(Test.WinForms.WSTenekRH.TraeVacacionesRequest request) {
            return base.Channel.TraeVacacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.WinForms.WSTenekRH.TraeVacacionesResponse> TraeVacacionesAsync(string numeroEmpleado) {
            Test.WinForms.WSTenekRH.TraeVacacionesRequest inValue = new Test.WinForms.WSTenekRH.TraeVacacionesRequest();
            inValue.Body = new Test.WinForms.WSTenekRH.TraeVacacionesRequestBody();
            inValue.Body.numeroEmpleado = numeroEmpleado;
            return ((Test.WinForms.WSTenekRH.ServicesSoap)(this)).TraeVacacionesAsync(inValue);
        }
    }
}
