//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenekRH.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Nomina = new HashSet<Nomina>();
            this.Usuario = new HashSet<Usuario>();
            this.Vacaciones = new HashSet<Vacaciones>();
        }
    
        public int EmpleadoID { get; set; }
        public int NumeroEmpleado { get; set; }
        public string ApellidosEmpleado { get; set; }
        public string NombresEmpleado { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string IdMensajeria { get; set; }
        public int PuestoId { get; set; }
        public int PerfilId { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual Puesto Puesto { get; set; }
        public virtual ICollection<Nomina> Nomina { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual ICollection<Vacaciones> Vacaciones { get; set; }
    }
}
