//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenekRH.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puesto
    {
        public Puesto()
        {
            this.Empleado = new HashSet<Empleado>();
        }
    
        public int PuestoId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Empleado> Empleado { get; set; }
    }
}
