//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenekRH.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacaciones
    {
        public int VacacionesId { get; set; }
        public int NumeroEmpleado { get; set; }
        public int Periodo { get; set; }
        public int DiasCorrespondientes { get; set; }
        public int DiasDisponibles { get; set; }
        public int DiasDisfrutados { get; set; }
        public decimal PorcentPrimaVacacional { get; set; }
        public int Vencimiento { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
